spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
management.endpoint.health.show-details=never
