spring.application.name=Ecomm
spring.datasource.url=jdbc:h2:mem:Db-ecom
spring.datasource.driverClassName = org.h2.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
server.port=8080
spring.jpa.defer-datasource-initialization=true   //"When we use an H2 database and run our project, Spring might try to connect to a table before JPA has finished creating it. This setting tells Spring to wait, so it only connects after the data and tables are fully loaded, preventing errors."